application: buzz-url
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/unittest/.*
  script: uneedtest.app
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
